#:schema node_modules/wrangler/config-schema.json
name = "tiktok"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[observability]
enabled = true

[vars]
MY_VARIABLE = "production_value"
#https://rapidapi.com/Lundehund/api/tiktok-api23

URL="https://tiktok-api23.p.rapidapi.com"
API_KEY="0014c60236mshe134e97474e6bf0p169e1ejsna7035bac56d3"
HOST="tiktok-api23.p.rapidapi.com"

BASIC_AUTH_USERNAME="admin"
BASIC_AUTH_PASSWORD="esGdZvlAugQoDaMHKJSzrpYnELuESi"
BASIC_AUTH_TOKEN="YWRtaW46ZXNHZFp2bEF1Z1FvRGFNSEtKU3pycFluRUx1RVNp"
