#:schema node_modules/wrangler/config-schema.json
name = "tiktok"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[observability]
enabled = true

[vars]
MY_VARIABLE = "production_value"
#https://rapidapi.com/Lundehund/api/tiktok-api23

URL="https://tiktok-api23.p.rapidapi.com"
API_KEY="cea948d6d2mshd002f56c45b18d3p17f11ejsnbfe77c860040"
HOST="tiktok-api23.p.rapidapi.com"

BASIC_AUTH_USERNAME="admin"
BASIC_AUTH_PASSWORD="esGdZvlAugQoDaMHKJSzrpYnELuESi"
BASIC_AUTH_TOKEN="YWRtaW46ZXNHZFp2bEF1Z1FvRGFNSEtKU3pycFluRUx1RVNp"
