name: Deploy

on:
  push:
    branches:
      - sandbox
    paths-ignore:
    - ".github/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Install package
        run: npm install --force
      - name: Deploy Workers
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          for i in {1..1}; do
            WORKER_NAME="tbk-tiktok-sb-$i"
            wrangler deploy --name $WORKER_NAME
          done
